services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/app/data/database.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  data:
